### ISSUE TITLE
Como administrador quiero consultarle al usuario si el trueque se finalizo con exito o no, para dejar registrado el fin de la transaccion. 

### ISSUE THREAD

**Issue by FacuRossi** [oktrueque/oktrueque#40]

**Comment by nicorios** [comment]
Modal cuando se loguea ( tener en cuenta si tiene varios trueques activos)
Enviar Email cada 5 dias consultando.
Cuando se confirma cambiar el estado de userTrueque y verificar si todos los participantes del trueque ya lo han confirmado, entocnes confirmar el trueque.
Dar de baja a los items.
Eliminar la conversacion.
